### ISSUE TITLE
Minor usability bugs in Userguide

### ISSUE THREAD

**Issue by xianlinc** [xianlinc/pe#4]
The term currently visible list is used here:

![Screenshot 2021-11-12 at 5.18.05 PM.png](https://raw.githubusercontent.com/xianlinc/pe/main/files/1a7cddc8-c27e-4c75-8003-5758fae5b139.png)

While in most other instances "displayed contacts list" is used:

![Screenshot 2021-11-12 at 5.19.20 PM.png](https://raw.githubusercontent.com/xianlinc/pe/main/files/f8bbc13a-ccd4-4ef0-bdfa-26af8a5bbb82.png)

**Comment by nus-se-script** [comment]
# Team's Response
Thanks for pointing this out. Our team has adopted "displayed contacts" list and provided links to that section as many features use this "displayed contacts".

However, we believe the different naming convention is not an issue as both terms convey the same meaning. As such, readers of the document will not be affected in any way.


# Items for the Tester to Verify
## :question: Issue response

Team chose [`response.Rejected`]



- [x] I disagree

**Reason for disagreement:** Readers of the document might still be affected as the terms that are used change. Even though the terms seem to convey the same meaning, this might not be so clear to a reader.

-------------------
